name: Spring boot docker image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Source Copy
      #   run: git clone https://github.com/hoonzzang617/kosa-devops-step2

      - uses: actions/checkout@v3

      - name: Setup JDK17 
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          
      - name: gradlew chmod +x
        run: chmod +x gradlew 
        
      - name: Test with gradle
        run: ./gradlew --info test

      - name: Spring Boot 
        run: ./gradlew bootJar

      - name: generate Docker Image
        run: docker build -t hoonzzang/devops_step2:v1.0 .

      # - name: docker login
      #   run: docker login -u hoonzzang -p${{ secrets.DOCKER_PASSWORD }}

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: hoonzzang
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker push 2 hub
        run: docker push hoonzzang/devops_step2:v1.0


  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: hoonzzang
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker image pull
        run: docker pull hoonzzang/devops_step2:v1.0



    
